language: python
python:
  - "3.8"
  - "3.9"
install:
  - python -m pip install --upgrade pip
  - pip install pipenv
  - export PIPENV_PIPFILE=API/Pipfile
  - pipenv install --dev
script:
  - pipenv run coverage run -m pytest

after_sucess:
  codecov
